module.exports = {
  preprocessor: require("./preprocessor"),
  lexer: require("./lexer"),
  parser: require("./parser"),
  analyzer: require("./analyzer"),
  compiler: require("./compiler"),
  compilerdriver: require("./compilerdriver"),
  utils: require("./utils"),
  scratch: require("./scratch"),
  analysisvalue: require("./analysisvalues"),
  ast: require("./ast"),
  isa: require("./isa"),
  adapters: require("fs-adapters"),
  version: require("../package.json").version,
};
